Sets by default the long date format on the date picker form type
sonata-project/form-extensions pull request #43
Opened 2019-08-08 07:55 UTC by DavidHernandez

## Subject

Sets by default the long date format to allow forms in Spanish to submit dates without extra configuration. 

## Branch
I'm targeting this branch because it fixes a small issue that affects only sites with a Spanish locale and using the `DatePicker` form type when using the default or medium DateType Format. This change will not break any existing site but it will change the format used in the form fields that are not directly changed to use a different format.

## Issue
The issue being resolved was originally reported on the `SonataAdminBundle`:
https://github.com/sonata-project/SonataAdminBundle/issues/5235

There is already a PR for this change on the old repository: https://github.com/sonata-project/SonataCoreBundle/pull/709

## Changelog

### Changed
- Changes the default DateType format on the DatePicker form type to prevent errors when using Spanish locale.

2019-08-08 08:00 UTC, DavidHernandez commented
## The before Medium format:
![Screenshot from 2019-08-08 09-44-54](https://user-images.githubusercontent.com/877002/62684698-84d6b100-b9c1-11e9-9df9-3ff4837ebde7.png)

It causes an error on save:
![Screenshot from 2019-08-08 09-45-06](https://user-images.githubusercontent.com/877002/62684719-928c3680-b9c1-11e9-8461-e9bda7de07c5.png)

## After changing the format:
![Screenshot from 2019-08-08 09-45-45](https://user-images.githubusercontent.com/877002/62684729-9c159e80-b9c1-11e9-8c06-ae75a26d312a.png)

It works properly:
![Screenshot from 2019-08-08 09-46-35](https://user-images.githubusercontent.com/877002/62684745-a20b7f80-b9c1-11e9-992c-8e4cd6adb3e6.png)

2019-08-08 19:39 UTC, phansys requested changes
Hi @DavidHernandez! Thank you so much for your first contribution.
I've read the thread starting from https://github.com/sonata-project/SonataAdminBundle/issues/5235, and if I understand correctly, there is no issue from the backend perspective.
If that is the case, I think this issue should be fixed in the configuration passed to the javascript date picker component instead of making changes at the current format.
Even, please take care that the visual change can break form layouts where the space is small.

2019-08-09 13:08 UTC, DavidHernandez commented
Hi @phansys,

As I understand it, the problem is in the backend. As it is the backend who sends the configuration to the javascript date picker library. The change addressed in this PR changes the configuration that it is passed to the frontend.

I agree that the long format may break some small screen layouts. If it is preferred, I can change it to use the short format, that just uses numbers.

Regards,
David.

2019-08-09 13:46 UTC, phansys commented
I mean, since the backend is providing the configuration for the frontend library, is there any way to change the configuration or the value passed to that library without changing what is currently presented in the input?
Otherwise this could break again if the user needs to use another format to represent the date, providing a different "format" option.

2019-08-09 13:51 UTC, DavidHernandez commented
If the user needs to use a different format, they can do it when they add the form element. That's how I avoided the issue on my project:

```
$formMapper->add('dueDate', DatePickerType::class, [
  'required' => true,
  'format' => \IntlDateFormatter::LONG,
]);
```

But if we keep the medium format, by default, it will be broken by default.

2019-11-09 19:53 UTC, core23 commented
Can you please add a test @DavidHernandez

2019-12-06 11:17 UTC, core23 commented
Ping @DavidHernandez

2020-01-31 09:01 UTC, closed without merging