chore: allowing support of Symfony  7
sonata-project/form-extensions pull request #462
Opened 2023-11-21 15:49 UTC by pauljosephkrogulec

##  allowing support of Symfony  7

I am targeting this branch, because is for allowing the possibility of use in symfony 7 project and don't create a BC-break

## Changelog

Allowing support of Symfony 7  (@pauljosephkrogulec)

```markdown
### Added
- Support of Symfony 7
```

2023-11-22 08:24 UTC, VincentLanglet requested changes

2023-11-22 08:24 UTC, VincentLanglet commented on composer.json
> +        "symfony/event-dispatcher": "^5.4 || ^6.2 || 7.0.*",
```suggestion
        "symfony/event-dispatcher": "^5.4 || ^6.2 || ^7.0",
```
To allow futur Symfony minor version.

2023-11-22 08:50 UTC, VincentLanglet commented
HI @pauljosephkrogulec

In order to support Symfony 7 we need to be able to run CI with it, like I tried 
here: https://github.com/sonata-project/EntityAuditBundle/pull/592/files#diff-245392b692a50c38ecab4381b118862db514035c10983f3bd4f4b7f1f4be4692R60-R64

But, currently SF 7 doesn't run on our build because of PHP-CS-Fixer, cf
https://github.com/sonata-project/EntityAuditBundle/actions/runs/6954735614/job/18922120160?pr=592

Let's wait an answer on https://github.com/PHP-CS-Fixer/PHP-CS-Fixer/pull/7431#issuecomment-1822341952

2023-11-23 08:56 UTC, VincentLanglet requested changes
Can you update the github actions like in https://github.com/sonata-project/twig-extensions/pull/392 in order to be sure that SF 7 can be installed ? Thanks

2023-11-23 09:39 UTC, VincentLanglet commented
You'll need
```
"matthiasnoback/symfony-config-test": "^4.2 || ^5.1",
"matthiasnoback/symfony-dependency-injection-test": "^4.0 || ^5.0",
```

2023-11-23 10:35 UTC, VincentLanglet commented
There is one test failure:
```
1) Sonata\Form\Tests\Type\FormChoiceWidgetTest::testLabelRendering
Failed asserting that '<div id="choice"><input type="checkbox" id="choice_0" name="choice[]" value="0"><label for="choice_0">[trans]some[/trans]</label><input type="checkbox" id="choice_1" name="choice[]" value="1"><label for="choice_1">[trans]choices[/trans]</label></div>' contains "<div id="choice"><input type="checkbox" id="choice_0" name="choice[]" value="0" /><label for="choice_0">[trans]some[/trans]</label><input type="checkbox" id="choice_1" name="choice[]" value="1" /><label for="choice_1">[trans]choices[/trans]</label></div>".
```

We'll need to understand what's changed in SF7

2023-11-23 13:39 UTC, pauljosephkrogulec commented
> There is one test failure:
> 
> ```
> 1) Sonata\Form\Tests\Type\FormChoiceWidgetTest::testLabelRendering
> Failed asserting that '<div id="choice"><input type="checkbox" id="choice_0" name="choice[]" value="0"><label for="choice_0">[trans]some[/trans]</label><input type="checkbox" id="choice_1" name="choice[]" value="1"><label for="choice_1">[trans]choices[/trans]</label></div>' contains "<div id="choice"><input type="checkbox" id="choice_0" name="choice[]" value="0" /><label for="choice_0">[trans]some[/trans]</label><input type="checkbox" id="choice_1" name="choice[]" value="1" /><label for="choice_1">[trans]choices[/trans]</label></div>".
> ```
> 
> We'll need to understand what's changed in SF7

The error is cause by the adding of / in the of the input (/> == >)

2023-11-23 13:41 UTC, VincentLanglet commented
> The error is cause by the adding of / in the of the input (/> => >)

Sure, but removing the `/` won't solve our issue. It will solve the error on SF7 but tests on SF5-6 will fail.
Also, does the html is still valid without the `/` ? Maybe Symfony has a regression which need to be reported...

2023-11-23 14:30 UTC, pauljosephkrogulec commented
> > The error is cause by the adding of / in the of the input (/> => >)
> 
> Sure, but removing the `/` won't solve our issue. It will solve the error on SF7 but tests on SF5-6 will fail. Also, does the html is still valid without the `/` ? Maybe Symfony has a regression which need to be reported...

The problem come from the bundle symfony/twig-bridge https://github.com/symfony/twig-bridge/commit/dcb5bb80aade1571fb28a4a57a0a65100c1252bd
I have a solution with a if but i don't know if good one using `Kernel::VERSION`

2023-11-23 14:33 UTC, VincentLanglet commented
> The problem come from the bundle symfony/twig-bridge [symfony/twig-bridge@dcb5bb8](https://github.com/symfony/twig-bridge/commit/dcb5bb80aade1571fb28a4a57a0a65100c1252bd) 

thanks for the research. So it's a "feature" from Symfony.

> I have a solution with a if but i don't know if good one using `Kernel::VERSION`

I would be ok with this.

2023-11-23 17:38 UTC, VincentLanglet approved these changes

2023-11-23 20:07 UTC, merged

2023-11-23 20:07 UTC, VincentLanglet commented
Thanks